// <auto-generated />
namespace LibraryService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CheckoutBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckoutBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "201404150413548_CheckoutBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
